### ISSUE TITLE
HungerGames : Can't join after a while

### ISSUE THREAD

**Issue by s0me-1** [vram4/Ogar#29] opened 2015-06-10 17:43 UTC
I don't really know why, after a while, we can't reach the server. It's not related to the host machine, because when we restart the server, we can join again. I think it happens when there are some people waiting but then everybody leaves and nobody is remaining.

No error in console, both client side and server side ;)

**Comment by s0me-1** [comment] 2015-06-11 18:09
Seems to be happening after the commit with autoFill ;)

**Comment by vram4** [comment] 2015-06-11 18:26
@s0me-1 Ah okay, that makes my job a lot easier. I spent alot of time trying to figure out how to reproduce the bug.

**Comment by s0me-1** [comment] 2015-06-11 19:09
It seems to be an infinite loop ! with your last commit, we saw that actualy the server was frozen, we can't type anything in the console

**Comment by s0me-1** [comment] 2015-06-11 19:21
Here's the config used :

serverMaxConnections = 64
serverPort = 500
serverGamemode = 11
serverBots = 0
serverViewBase = 1024
borderLeft = 0
borderRight = 6000
borderTop = 0
borderBottom = 6000
spawnInterval = 20
foodSpawnAmount = 10
foodStartAmount = 100
foodMaxAmount = 500
foodMass = 1
virusMinAmount = 10
virusMaxAmount = 50
virusStartMass = 100
virusBurstMass = 198
ejectMass = 16
ejectMassGain = 12.8
ejectSpeed = 160
ejectSpawnPlayer = 50
playerStartMass = 10
playerMaxMass = 22500
playerMinMassEject = 32
playerMinMassSplit = 36
playerMaxCells = 16
playerRecombineTime = 15
playerMassDecayRate = 0.004
playerMinMassDecay = 9
tourneyMaxPlayers = 12
tourneyPrepTime = 5
tourneyEndTime = 15
tourneyAutoFill = 15

**Comment by vram4** [comment] 2015-06-11 19:42
@s0me-1 Do you still get the freezes when tourneyAutoFill is set to 0?

**Comment by s0me-1** [comment] 2015-06-11 19:47
we're testing right now, we need some players to launch a game an comfirm that to make sure it's a bot-related problem

**Comment by vram4** [comment] 2015-06-11 20:44
@s0me-1 The problem seems to be caused by having a long name while in hunger games gamemode

**Comment by Ephemerality** [comment] 2015-06-11 20:53
Should be limited to 15 after latest commit, shouldn't it?

**Comment by vram4** [comment] 2015-06-11 21:00
I found the problem: When there are no players and you press "q" while typing a name, the server tries to find a spectator from the list of players, but there arent any players, so it gets stuck in a loop. A fix will be applied soon.

**Comment by Ephemerality** [comment] 2015-06-11 21:01
Ah, my bad. Thought I set it up to avoid that if it looped once and didn't find any!

**Comment by vram4** [comment] 2015-06-11 21:07
@Ephemerality I need to go somewhere soon, so i made a quick fix for this, improve it if you want.

**Closed by vram4** 2015-06-11 21:07 UTC
Labels: In Progress

**Comment by s0me-1** [comment] 2015-06-11 21:23
Well, that was a tough one ! Good job for finding out ! :)

**Comment by Ephemerality** [comment] 2015-06-11 22:21
Give the latest a try. The code is less than elegant, but it seemed to work in my testing...

**Comment by s0me-1** [comment] 2015-06-12 21:44
seems to work, ty :)
