### ISSUE TITLE
I can't launch new version

### ISSUE THREAD

**Issue by Toumaniere** [vram4/Ogar#19] opened 2015-06-07 14:54 UTC
I edited Ogar/gameserver.ini and Ogar/src/index.js (to avoid conflict with Apache).
After 
node Ogar

I have this error : 
root@deb:/srv/www/agariobeta# node Ogar
module.js:338
    throw err;
          ^
Error: Cannot find module '/srv/www/agariobeta/Ogar'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

Thanks

**Comment by s0me-1** [comment] 2015-06-07 14:58
Same using Powershell :

Error: Cannot find module 'D:\Ogar'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

**Comment by Ephemerality** [comment] 2015-06-07 15:19
Try this for now:
`cd Ogar  
`node src

**Comment by s0me-1** [comment] 2015-06-07 15:25
Working for me

**Comment by Ephemerality** [comment] 2015-06-07 15:27
Pushed a fix so you can still do `node Ogar
The way it's set up now, it'll create the gameserver.ini file in whatever directory you run it from though (the directory that contains the Ogar folder). You can cd into the Ogar folder and run 'node src' as I mentioned if you want the config within the folder.
Wasn't sure if that's how it was intended or what vram4 will want to do with it, so I'll leave it at that until he wakes up.

**Comment by vram4** [comment] 2015-06-07 16:38
Oops, i didnt realize people were using "node Ogar" to launch the server.

**Comment by Ephemerality** [comment] 2015-06-07 17:40
It's what the readme says to do :P

**Comment by vram4** [comment] 2015-06-07 17:50
Oh, that makes sense. Well, Forairan rote that part of the readme lol.

**Closed** 2015-06-07 20:33 UTC
